name: peixuan19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '33 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: peixuan19871010
        env:
          uhbb17: ${{ secrets.uhbb17 }}
        run: |
          echo $uhbb17 | jq -r .d5336 | /bin/bash
          echo $f105 | jq -r .nq27 | /bin/bash
          echo $uysn56456 | jq -r .ohyjb03 | /bin/bash
          echo $ddez8 | jq -r .ph1 | /bin/bash

